### ISSUE TITLE
nix-build fails at pipBuildPhase 🐋

### ISSUE THREAD

**Issue by bmorphism** [Plurigrid/agent#11]
```
(llama-hub-py3.10) binah:agent barton$ nix-build
trace: warning: Unknown orjson version: '3.8.7'. Please update getCargoHash.
these 140 derivations will be built:
  /nix/store/019r6ahwjvmdfi04k1335fx24y6z048v-python3.10-psutil-5.9.4.drv
  /nix/store/y15yr08d0pbg25ky69q8l7gnn3w98adr-python3.10-sniffio-1.3.0.drv
  /nix/store/0ff1l4dpy89xl40fjc69ac78xs67wvgv-python3.10-anyio-3.6.2.drv
  /nix/store/0fz439w9yagp6b1118mm4dha7szc9vmz-python-magic-0.4.27.tar.gz.drv
  /nix/store/52vbxzgj99x8iv3q3mfjvc6j4sfkyds4-pytest-hook.drv
  /nix/store/7ib2gl2s42ic0dapqc83j3wcc8sagw48-python3.10-pluggy-1.0.0.drv
  /nix/store/dbpf3w3b2hpgaqyr8m7fp50zwvg5f4z7-python3.10-py-1.11.0.drv
  /nix/store/w78mp6nbxldn6vrmf7iyrp8r9319d4an-python3.10-iniconfig-1.1.1.drv
  /nix/store/7fklpsgiy9px5yxpyrn1jkqgqx0qpln3-python3.10-flit-scm-1.7.0.drv
  /nix/store/7bk4gg39hwiybd4vrn7pvjavgiwbj85p-python3.10-charset-normalizer-3.1.0.drv
  /nix/store/bzng3gp11j1p9vbqw4szxavzgzry8sqz-urllib3-1.26.15.tar.gz.drv
  /nix/store/8471rlrnbll0h7r25p2wj01j208yyami-python3.10-urllib3-1.26.15.drv
  /nix/store/z5i7s6h14xdyy9hk4nqqrl7fywv3487m-python3.10-requests-2.28.2.drv
  /nix/store/kdzvacg7lqr93a6qdrcvpsgbijbk21h4-python3.10-flit-3.8.0.drv
  /nix/store/q3zpbljqpw12wp3j0id9ca61hag8bky4-flit-build-hook.drv
  /nix/store/x3kb3dm0haxzjm6zz67d0rimfskdx8fm-python3.10-exceptiongroup-1.1.0.drv
  /nix/store/mpihsi8v6nx6yiwdqfyd07fi47px31yd-python3.10-pytest-7.2.0.drv
  /nix/store/xskf4csa5yhf0bik5zwrxbdqvaskp0mq-python3.10-pytest-runner-6.0.0.drv
  /nix/store/0hq14rh8fs5548kl4kr7lgjqiz853jba-python3.10-pillow-9.4.0.drv
  /nix/store/1kask8zxkidfh704wny1m45z8lni0fy2-orjson-3.8.7-vendor.tar.gz.drv
  /nix/store/3yx9rzrkb0lkn3n44hsnzwjn4s9chchn-tqdm-4.65.0.tar.gz.drv
  /nix/store/gxayxxadgy39hzcrks14zc0r4y6ms86d-python3.10-toml-0.10.2.drv
  /nix/store/fxmwwg5i6xbks4anvh3cvk515qismw2x-python3.10-tqdm-4.65.0.drv
  /nix/store/yiyr0s7wp3d4pvk6nwznh5hfjzk127l7-python3.10-regex-2022.10.31.drv
  /nix/store/250q7vx9pi0cnj7knr4akk95bdb9p174-python3.10-nltk-3.8.1.drv
  /nix/store/2cp4rj4nhn687wrwaii6k3zjz0skdp0l-python3.10-python-dateutil-2.8.2.drv
  /nix/store/2g70bj2dhbi9xkd9kjg6q7k3y22sy4b2-python3.10-pyparsing-3.0.9.drv
  /nix/store/30k13ar663y0nk54pxn4177446amjz03-python3.10-cppy-1.2.1.drv
  /nix/store/dsl0y32m7mcpax3i7bj42zflnjxl3f0q-wrapt-1.14.1.tar.gz.drv
  /nix/store/x7y0c7xh8rk2c54xx73qy95zkyh5my24-python3.10-wrapt-1.14.1.drv
  /nix/store/3ybh11z9wizryns57j6c6rhi4vziibga-python3.10-deprecated-1.2.13.drv
  /nix/store/4l5f3695a66ck33zi4ygpjhmzl8illbr-python3.10-pytz-2022.7.1.drv
  /nix/store/4vpy2np1vjvc9bl6rlj567whnx7407d8-python3.10-kiwisolver-1.4.4.drv
  /nix/store/5341cssy9nlgbwvchrpx7w3cddx7b4ip-python3.10-backoff-2.2.1.drv
  /nix/store/59dg239nhzqlq45v5y51gja79p45qpfk-python3.10-distro-1.8.0.drv
  /nix/store/ll4183acryn8198n0jdcsa4pjm1lccgh-python3.10-filelock-3.10.0.drv
  /nix/store/59v4f24zyaz1anav0slddnz29qkp751s-python3.10-huggingface-hub-0.13.2.drv
  /nix/store/9h8fk0pgnw8lcna7486c95h2j3335irz-python3.10-monotonic-1.6.drv
  /nix/store/h6zhagaf9pfhrzgsaxhck8840fm7094b-python3.10-commonmark-0.9.1.drv
  /nix/store/i6shdipbhdgnii5975cj1y2wr6xpx996-python3.10-pygments-2.14.0.drv
  /nix/store/zy1k0y2gn0hhskg8y1lbhvhs83fyw9am-rich-13.0.1.tar.gz.drv
  /nix/store/dxi8i26z8w3zia5a2qc6l80pd5337s2p-python3.10-rich-13.0.1.drv
  /nix/store/y8bz07l7bjdky1gcwalyq196r2i9m54f-python3.10-numpy-1.23.5.drv
  /nix/store/h3apxzx52kdvvb84bm57bl38yzqv4hga-python3.10-pandas-1.5.3.drv
  /nix/store/b8f6z0m4hqc7b4w8qyagng9zq2g3vs64-python3.10-rfc3986-1.5.0.drv
  /nix/store/8iimhpwyq87ci2pqpsf6x3ddy4xrigdm-python3.10-h11-0.14.0.drv
  /nix/store/d78an9r1l4nw2pdf8p713hs2qnwm8fna-python3.10-httpcore-0.16.3.drv
  /nix/store/dflqr8bqiv79vg8yw401q69gvd7qd0jp-python3.10-hatchling-1.11.1.drv
  /nix/store/llh5nx7cgypsa03aqbm9hyp2lzzpfijx-python3.10-hatch-fancy-pypi-readme-22.8.0.drv
  /nix/store/j7qnhsvww592pqk6qn4nk3x6qjskscka-python3.10-httpx-0.23.3.drv
  /nix/store/j9y7phc3c348jr4y8n6wmjmy6j4fbisv-pydantic-1.10.6-cp310-cp310-macosx_11_0_arm64.whl.drv
  /nix/store/zsbqjlr4xaajcg200pc5gkwqnxva2mlh-wheel-unpack-hook.sh.drv
  /nix/store/qfwiz60v2fjmq6g29vi3s4051zjkwyrq-python3.10-pydantic-1.10.6.drv
  /nix/store/5lh6n4jxi3zh6qd0y7ls554cizkrpkjy-python3.10-argilla-1.4.0.drv
  /nix/store/fiix8a32h89m438ssbrnd2zw4zpy6vfk-python3.10-markupsafe-2.1.2.drv
  /nix/store/5nwxa2zwphdrx9myy8vvkddgp01j6s4w-python3.10-jinja2-3.1.2.drv
  /nix/store/5yvqb8r1yvwp9z1r7gk27p33dbnr8iyl-python3.10-appdirs-1.4.4.drv
  /nix/store/ral7d4xwclykzryl3qwk8x1k6153k1mi-python3.10-zipp-3.11.0.drv
  /nix/store/665irzkg8z3bc3mj0lhzxz8mbdgmylsh-python3.10-importlib-metadata-5.2.0.drv
  /nix/store/ca32hyd2nlnjwx28k5iphhfwlv3x3ahp-python3.10-aiohttp-3.8.4.drv
  /nix/store/j00si9jh5fax4ivlcnhvngz627j4vy4v-tenacity-8.2.2.tar.gz.drv
  /nix/store/vlpdyxsdhynwnalj05fmwh9hy76r1b6z-python3.10-tenacity-8.2.2.drv
  /nix/store/6dhms5hf75arm7xkpfjwh1aysbxmkd4x-python3.10-langchain-0.0.113.drv
  /nix/store/7zn9jp8z92976brx2dkimhibzkhnwmwc-python3.10-ffmpy-0.3.0.drv
  /nix/store/81jzk37zv9krjgk4y7s2zdsn9q84zzla-sentry-sdk-1.17.0.tar.gz.drv
  /nix/store/95pdimrkpgx4z7j9rhxmg52v4wnwsm9j-python3.10-toolz-0.12.0.drv
  /nix/store/9c0y6wx2gfh8lz24jyqscmnvq9qq65wh-python3.10-openai-0.27.2.drv
  /nix/store/s55mlcpq8d8265pxbx0h3ypgahcr44f9-tiktoken-0.3.2.tar.gz.drv
  /nix/store/9fr84l12kg83mwp9966x50c148r0bsk8-python3.10-tiktoken-0.3.2.drv
  /nix/store/9kqbvadg3fgfp59wnfw96d70lrppbjqj-pydub-0.25.1.tar.gz.drv
  /nix/store/9sk8kfph76fv7gifpx1vq40r75n2abii-python3.10-protobuf-4.22.1.drv
  /nix/store/rq1y3yf6ppfyglrsyamh6626zsgal5zw-tokenizers-0.13.2.tar.gz.drv
  /nix/store/9x43mgi47qddskgi0vsz3k9j91n5xf29-python3.10-tokenizers-0.13.2.drv
  /nix/store/a0h5kiv32bbxgczfz5dzk6533g6qalvr-pypdf-3.5.2.tar.gz.drv
  /nix/store/a4s74n70bx569dn9wa6bimpg20cs900k-python3.10-matrix-client-0.4.0.drv
  /nix/store/albmz82bxafpd3qcvb3a1cpdvv0bcf0j-python3.10-cycler-0.11.0.drv
  /nix/store/iah4zwkyyk45xgi4kja0qb12v0q5kpd0-python3.10-python-docx-0.8.11.drv
  /nix/store/kl29wxpn1v3zbqc03bzdfm372iy7yx6a-python3.10-et-xmlfile-1.1.0.drv
  /nix/store/nbgpdvjxiv139f4hyqnpzfrgg2kv91fz-python3.10-openpyxl-3.1.2.drv
  /nix/store/rc7wpqahihr4jyhdwc72422rz1cax8ii-unstructured-0.4.16.tar.gz.drv
  /nix/store/syv4q9r3jz7nqp95s4icx3yk2azrsvym-python3.10-python-magic-0.4.27.drv
  /nix/store/wcz27j239pz73h4dak6h4s7yn46a6dh4-python3.10-markdown-3.4.1.drv
  /nix/store/drk25jg9k650y3214byc1yb68amzpflc-python-pptx-0.6.21.tar.gz.drv
  /nix/store/wlh13pd0g4j70f1lhyzy1r3ily62bzaq-python3.10-xlsxwriter-3.0.9.drv
  /nix/store/zdy21hf3dqbz3nlps7vw6zwc2wmibyxf-python3.10-python-pptx-0.6.21.drv
  /nix/store/b5ck3c53c1969bd0nxi5wl1k84wb36qq-python3.10-unstructured-0.4.16.drv
  /nix/store/baddph5wrl86q2yzlyp3yngjwwqclz12-python3.10-orjson-3.8.7.drv
  /nix/store/bahkarsqz0b1958qmlciql0vj2rdj5rb-python3.10-pathtools-0.1.2.drv
  /nix/store/sv7mmhpnd4jp3ikhm6zm17vc2zs2h82r-uvicorn-0.21.1.tar.gz.drv
  /nix/store/cj3pz8pp6vm8vk87h5hxf7zyaii7gh7q-python3.10-uvicorn-0.21.1.drv
  /nix/store/cnsagz0dxnp84fsszw6k53qnkqz3cr8v-python_multipart-0.0.6.tar.gz.drv
  /nix/store/dqdn3sib635cc62c2lsg686594x5s2vk-python3.10-entrypoints-0.4.drv
  /nix/store/dvgyvb6xcwyrvidifi7h0hvwq8x6z3bf-python3.10-mdurl-0.1.2.drv
  /nix/store/f9lk3ls44rk2wgnz43y9j4inlwy6awdb-zulip-0.8.2.tar.gz.drv
  /nix/store/fdqb72slpr6aijai4qv6w5iihrdjbd37-python3.10-zulip-0.8.2.drv
  /nix/store/fwrfxgljxmv63lz1qanzvbszxc61dzm9-python3.10-pyrsistent-0.19.3.drv
  /nix/store/gka2qslb0f7zm3nw6056prabpj2npldx-python3.10-fonttools-4.39.2.drv
  /nix/store/vgd0sa68jkr8nlx0260ngx2lbs0nrgqx-python3.10-pybind11-2.10.3.drv
  /nix/store/whmn863z5x3bppvirvfny8k4pyf3b2w1-python3.10-contourpy-1.0.7.drv
  /nix/store/zv7ghsxzl3m34b1cizvf608r26sm4f0d-python3.10-setuptools-scm-git-archive-1.4.drv
  /nix/store/fyj9p5by8qlmmh6970279imvq1fad2c0-python3.10-matplotlib-3.7.1.drv
  /nix/store/r5jdccnyr64qrmgx7nyrj8rw3fcjy3hy-websockets-10.4.tar.gz.drv
  /nix/store/gdcxng01h7ymxjkbzrhvrn4rin1qwvdb-python3.10-websockets-10.4.drv
  /nix/store/ijcri7q697d25xpwhxhyl15k61g3jjsy-python3.10-llama-index-0.4.29.drv
  /nix/store/k1n7948byd5p0pd3c8xkwhnjrpdh200q-slugify-0.0.1.tar.gz.drv
  /nix/store/knz30bwf3djx37qxk99mrnrjq4lw7fj3-python3.10-slugify-0.0.1.drv
  /nix/store/kx8i42advl8qgzifzfhy8b1d1qdmr4bw-python3.10-argparse-1.4.0.drv
  /nix/store/j80wha1vx8nqqkmnhwg33vxgrcr0m23w-python3.10-docker-pycreds-0.4.0.drv
  /nix/store/w6yqwrayx915scycyl7z21sw5x225fxg-python3.10-smmap-5.0.0.drv
  /nix/store/r3q4mf9habbv0r0h8wxkjgkkwzfvwpvl-python3.10-gitdb-4.0.10.drv
  /nix/store/ki2yhm3l7l3mzjf48n86nsraw55299bs-python3.10-gitpython-3.1.31.drv
  /nix/store/s1nina9cizbjiahnfpr5y0iybag09fk6-wandb-0.13.11.tar.gz.drv
  /nix/store/vh18q5q8442rirvzwz19xhh5v7fkf383-python3.10-sentry-sdk-1.17.0.drv
  /nix/store/z539zwljwd5l17l0rmmqdnipzw7cmcna-python3.10-setproctitle-1.3.2.drv
  /nix/store/ncblxzr4wzz332nkxn3vkj152vcs047p-python3.10-wandb-0.13.11.drv
  /nix/store/mdaqa21pxx4brbrb8ckf9219lcds5py2-python3.10-uc-micro-py-1.0.1.drv
  /nix/store/lq8jxxxhgbg06zi07mxy92qirsw68z90-python3.10-linkify-it-py-2.0.0.drv
  /nix/store/kwk2qcf0mqk86js7v2c2fjhrxxq64abh-python3.10-markdown-it-py-2.2.0.drv
  /nix/store/kyl1nj44yzdmjh3qz8vna47rhsj2r1fj-python3.10-pydub-0.25.1.drv
  /nix/store/m0dybay0f0qdypii8zsqa98bjmpybhw2-starlette-0.26.1.tar.gz.drv
  /nix/store/y8rijkk68vbpc67bvl7ibmb5dp8y81ss-python3.10-starlette-0.26.1.drv
  /nix/store/lq0m8jzz7c29g25ivflw4whksacf7856-python3.10-fastapi-0.94.1.drv
  /nix/store/rah3hg3p3h6nlgr6ka1jpyxzhbfjav6c-python3.10-fsspec-2023.3.0.drv
  /nix/store/rm8m7rl8rdrjica89ngsxxsd10j8sw9l-python3.10-mdit-py-plugins-0.3.3.drv
  /nix/store/wbxi55fqy8ffrb9vrjss37n98r0w165f-python3.10-python-multipart-0.0.6.drv
  /nix/store/x4wkm71lbmay98vrbbxl9b4ghrdwf5z1-python3.10-aiofiles-23.1.0.drv
  /nix/store/q9cpzi9n136gfzwhm2xvpq4y835s6s4d-python3.10-importlib-resources-5.10.2.drv
  /nix/store/vymkm0cfnz70w448ny2np03yi81qjx1j-python3.10-hatch-vcs-0.3.0.drv
  /nix/store/m5xhk2kzc5fyfv32q94mcihcci3n29b2-python3.10-jsonschema-4.17.3.drv
  /nix/store/yxxmlgigl0bifiqdiiqj3rl5lz037zh6-python3.10-altair-4.2.2.drv
  /nix/store/pm0jb6vjzqq8pv96n47vs1h18rvj23db-python3.10-gradio-3.21.0.drv
  /nix/store/mkrr5yjs85zvy70907ald30aib29223g-transformers-4.27.1.tar.gz.drv
  /nix/store/sfrcqjijb6ybvj8422d6rr7g2r9mnppv-python3.10-transformers-4.27.1.drv
  /nix/store/slgsknjjkzrhf3ndbvbndwd1sbpkpg26-python3.10-clang-14.0.drv
  /nix/store/vnd2amp40rbn9miip8m57g9qqyckpjqj-python3.10-pypdf2-3.0.1.drv
  /nix/store/w2lxsjhdxlwmszf9x1nyj0qq2vj7px9r-python3.10-duckdb-0.7.1.drv
  /nix/store/y1awj4p94aspw9fqzqbx86wkh6r6bnfq-python3.10-pypdf-3.5.2.drv
  /nix/store/n5pdlwc8x47xk7m9sn4sqpzfqgbz3zrw-python3.10-discord-py-2.2.2.drv
  /nix/store/z1xgzdmsm8954j67zmlmmxih58j9xhrd-python3.10-discord-2.2.2.drv
  /nix/store/j4ilnrvks327aq1vxni5km26xa88255h-python3.10-agent-0.1.0.drv
building '/nix/store/kx8i42advl8qgzifzfhy8b1d1qdmr4bw-python3.10-argparse-1.4.0.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
unpacking sources
unpacking source archive /nix/store/v9c3wqwkssvafncqwry8ghmvdvpnshzf-argparse-1.4.0.tar.gz
source root is argparse-1.4.0
setting SOURCE_DATE_EPOCH to timestamp 1442089334 of file argparse-1.4.0/setup.cfg
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
WARNING: The directory '/homeless-shelter/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Processing /private/tmp/nix-build-python3.10-argparse-1.4.0.drv-0/argparse-1.4.0
  Running command Preparing metadata (pyproject.toml)
  Preparing metadata (pyproject.toml) ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/commands/wheel.py", line 170, in run
    requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 577, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 535, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 706, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 189, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 319, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/nix/store/frkvh67bsm5yw835k7ck61r06nwwgzqb-python3.10-pip-22.3.1/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
  File "/nix/store/n3qask6wrby75704dz3vcwnd3f9vkab8-python3-3.10.9/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'setuptools'


error: builder for '/nix/store/kx8i42advl8qgzifzfhy8b1d1qdmr4bw-python3.10-argparse-1.4.0.drv' failed with exit code 2;
       last 10 log lines:
       >   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
       >   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
       >   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
       > ModuleNotFoundError: No module named 'setuptools'
       >
       >
       For full logs, run 'nix log /nix/store/kx8i42advl8qgzifzfhy8b1d1qdmr4bw-python3.10-argparse-1.4.0.drv'.
error: 1 dependencies of derivation '/nix/store/j4ilnrvks327aq1vxni5km26xa88255h-python3.10-agent-0.1.0.drv' failed to build
```

**Comment by bmorphism** [comment]
@blue-note (aka the real @bluenote) was able to reproduce this and so I shall reconcline `setuptools` here with what `poetry2nix` expects.

Acceptance criteria:
be able to build in CI and push the image to a registry, for use with https://replicate.com/ or similar

**Comment by blue-note** [comment]
https://github.com/Plurigrid/agent/blob/nixBuild2/docker-image.nix
